version: '2'

services:
  mariadb:
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "./data-mysql:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=my_database"
      - "MYSQL_USER=my_user"
      - "MYSQL_PASSWORD=my_password"
      - "MYSQL_ROOT_PASSWORD=docker"
    ports:
      - "3306:3306"
  myapp:
    tty: true
    image: bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: docker
