version: '3'

services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - ./data-mysql:/bitnami/mariadb
    environment:
      - MARIADB_EXTRA_FLAGS=--innodb-buffer-pool-size=20M
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_ROOT_PASSWORD=docker
      - MARIADB_DATABASE=my_database
    ports:
      - 3306:3306
  myapp:
    tty: true
    build: .
    links:
      - mariadb:mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./public_html:/app 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: docker
